import { useEffect, useMemo, useState } from 'react'
import { bookAppointment, getDoctors, getSlots } from '../../api/appointments'

const list = (value) => Array.isArray(value) ? value : value?.results || value?.doctors || value?.slots || []
export default function PatientHome() {
 const [doctors, setDoctors] = useState([]), [specialty, setSpecialty] = useState(''), [doctor, setDoctor] = useState(null), [slots, setSlots] = useState([]), [loading, setLoading] = useState(true), [loadingSlots, setLoadingSlots] = useState(false), [message, setMessage] = useState(''), [error, setError] = useState(''), [booking, setBooking] = useState(false)
 const specialties = useMemo(() => [...new Set(doctors.map((d) => d.specialty).filter(Boolean))].sort(), [doctors])
 const shownDoctors = specialty ? doctors.filter((d) => d.specialty === specialty) : doctors
 useEffect(() => { getDoctors().then((data) => setDoctors(list(data))).catch(() => setError('Could not load doctors.')).finally(() => setLoading(false)) }, [])
 async function selectDoctor(next) { setDoctor(next); setLoadingSlots(true); setSlots([]); setError(''); try { const data = await getSlots(next.id); const today = new Date().toISOString().slice(0, 10); setSlots(list(data).filter((slot) => !slot.is_booked && slot.date >= today)) } catch { setError('Could not load this doctor’s available slots.') } finally { setLoadingSlots(false) } }
 async function book(slot) { setBooking(true); setError(''); try { await bookAppointment(slot.id); setMessage(`Your appointment with ${doctor.name} on ${slot.date} at ${slot.start_time?.slice(0, 5)} is confirmed.`); await selectDoctor(doctor) } catch { setError('This slot is no longer available. The available times have been refreshed.'); await selectDoctor(doctor) } finally { setBooking(false) } }
 return <div className="mx-auto max-w-5xl px-5 py-10 sm:px-6 sm:py-14"><p className="text-xs font-semibold uppercase tracking-[.16em] text-ink/55">Patient portal</p><h1 className="mt-2 font-display text-4xl font-bold">Book an appointment</h1><p className="mt-3 text-sm text-ink/65">Choose a doctor, then select an available future time.</p>{message && <p className="mt-5 border-l-4 border-status-ok bg-status-ok/10 p-3 text-sm">{message}</p>}{error && <p className="mt-5 border-l-4 border-status-alert bg-status-alert/10 p-3 text-sm">{error}</p>}<div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="border border-ink/15 bg-panel p-5"><label className="block text-sm font-semibold">Filter by specialty<select value={specialty} onChange={(e) => { setSpecialty(e.target.value); setDoctor(null); setSlots([]) }} className="mt-2 w-full border border-ink/25 p-3 font-normal"><option value="">All specialties</option>{specialties.map((name) => <option key={name}>{name}</option>)}</select></label><h2 className="mt-6 font-display text-2xl font-bold">Doctors</h2>{loading ? <p className="mt-4 text-sm text-ink/60">Loading doctors...</p> : shownDoctors.length ? <div className="mt-4 space-y-3">{shownDoctors.map((item) => <button key={item.id} onClick={() => selectDoctor(item)} className={`w-full border p-4 text-left ${doctor?.id === item.id ? 'border-ink bg-ink/5' : 'border-ink/15'}`}><p className="font-semibold">{item.name}</p><p className="mt-1 text-sm text-ink/60">{item.specialty}</p>{item.bio && <p className="mt-2 text-xs text-ink/55">{item.bio}</p>}</button>)}</div> : <p className="mt-4 text-sm text-ink/65">No doctors match this specialty.</p>}</section><section className="border border-ink/15 bg-panel p-5"><h2 className="font-display text-2xl font-bold">Available slots</h2>{!doctor ? <p className="mt-4 text-sm text-ink/65">Select a doctor to view available times.</p> : loadingSlots ? <p className="mt-4 text-sm text-ink/60">Loading available slots...</p> : slots.length ? <div className="mt-4 grid grid-cols-2 gap-3">{slots.map((slot) => <button disabled={booking} key={slot.id} onClick={() => book(slot)} className="border border-ink/15 p-3 text-left hover:border-ink disabled:opacity-50"><p className="font-semibold">{slot.start_time?.slice(0, 5)}</p><p className="mt-1 text-xs text-ink/55">{slot.date}</p></button>)}</div> : <p className="mt-4 text-sm text-ink/65">No available future slots for this doctor.</p>}</section></div></div>
}
