import { useEffect, useState } from 'react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import { getDoctorAppointments, recordTreatment, saveDiagnosis } from '../../api/doctor'
const asList = (data) => Array.isArray(data) ? data : data?.appointments || data?.results || []
export default function DoctorAppointments() { const { id } = useParams(); const location = useLocation(); const navigate = useNavigate(); const [appointment, setAppointment] = useState(location.state?.appointment); const [diagnosis, setDiagnosis] = useState(location.state?.appointment?.diagnosis || ''); const [treatment, setTreatment] = useState(location.state?.appointment?.treatment || ''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
 useEffect(() => { if (!appointment) getDoctorAppointments().then((data) => { const item = asList(data).find((value) => String(value.id) === id); setAppointment(item); setDiagnosis(item?.diagnosis || ''); setTreatment(item?.treatment || '') }).catch(() => setError('Could not load this appointment.')) }, [appointment, id])
 if (!appointment && !error) return <p className="p-10 text-center text-sm text-ink/60">Loading appointment...</p>
 async function saveOnly() { setSaving(true); setError(''); try { await saveDiagnosis(id, diagnosis); setMessage('Diagnosis saved.') } catch { setError('Could not save the diagnosis.') } finally { setSaving(false) } }
 async function complete(e) { e.preventDefault(); setSaving(true); setError(''); try { await recordTreatment(id, { diagnosis, treatment }); setMessage('Treatment saved. This appointment is now completed.'); setTimeout(() => navigate('/doctor/history'), 700) } catch { setError('Could not save the treatment.') } finally { setSaving(false) } }
 return <form onSubmit={complete} className="mx-auto max-w-2xl px-5 py-10 sm:px-6 sm:py-14"><Link to="/doctor" className="text-sm font-semibold underline">← Upcoming appointments</Link><p className="mt-8 text-xs font-semibold uppercase tracking-[.16em] text-ink/55">Clinical entry</p><h1 className="mt-2 font-display text-3xl font-bold">{appointment?.patient_username}</h1><p className="mt-2 text-sm text-ink/65">{appointment?.date} · {appointment?.scheduled_time?.slice(0, 5)}</p>{message && <p className="mt-5 border-l-4 border-status-ok bg-status-ok/10 p-3 text-sm">{message}</p>}{error && <p className="mt-5 border-l-4 border-status-alert bg-status-alert/10 p-3 text-sm">{error}</p>}<div className="mt-7 border border-ink/15 bg-panel p-5"><label className="block text-sm font-semibold">Diagnosis<textarea value={diagnosis} onChange={(e) => setDiagnosis(e.target.value)} className="mt-2 min-h-28 w-full border border-ink/25 p-3 font-normal" /></label><button type="button" disabled={saving} onClick={saveOnly} className="mt-3 border border-ink/25 px-4 py-2 text-sm font-semibold disabled:opacity-50">Save diagnosis</button><label className="mt-6 block text-sm font-semibold">Treatment<textarea required value={treatment} onChange={(e) => setTreatment(e.target.value)} className="mt-2 min-h-32 w-full border border-ink/25 p-3 font-normal" /></label><p className="mt-2 text-xs text-ink/55">Submitting treatment marks this appointment as completed.</p><button disabled={saving || !treatment.trim()} className="mt-5 bg-ink px-5 py-3 text-sm font-bold text-panel disabled:opacity-50">{saving ? 'Saving...' : 'Save treatment and complete'}</button></div></form> }
