import { useEffect, useState } from 'react'
import { getDoctors } from '../../api/appointments'
import { getAdminAppointments, updateAppointmentStatus } from '../../api/adminAppointments'
import AppointmentStatus from '../../components/AppointmentStatus'
const list = (data) => Array.isArray(data) ? data : data?.results || data?.appointments || []
const statuses = ['pending', 'confirmed', 'completed', 'cancelled']
export default function AdminHome() { const [doctors, setDoctors] = useState([]), [items, setItems] = useState([]), [filters, setFilters] = useState({ doctor: '', date: '', status: '' }), [loading, setLoading] = useState(true), [error, setError] = useState(''), [saving, setSaving] = useState(null)
 async function load(next = filters) { setLoading(true); setError(''); try { const data = await getAdminAppointments(next); setItems(list(data)) } catch { setError('Could not load appointments.') } finally { setLoading(false) } }
 useEffect(() => { Promise.all([getDoctors(), getAdminAppointments({})]).then(([doctorData, appointmentData]) => { setDoctors(list(doctorData)); setItems(list(appointmentData)) }).catch(() => setError('Could not load appointments.')).finally(() => setLoading(false)) }, [])
 async function changeStatus(id, status) { setSaving(id); try { const updated = await updateAppointmentStatus(id, status); setItems((current) => current.map((item) => item.id === id ? { ...item, ...updated, status } : item)) } catch { setError('Could not update the appointment status.') } finally { setSaving(null) } }
 return <div className="mx-auto max-w-6xl px-5 py-10 sm:px-6 sm:py-14"><p className="text-xs font-semibold uppercase tracking-[.16em] text-ink/55">Admin portal</p><h1 className="mt-2 font-display text-4xl font-bold">Appointment management</h1><p className="mt-3 text-sm text-ink/65">Review bookings and keep appointment statuses current.</p>{error && <p className="mt-5 border-l-4 border-status-alert bg-status-alert/10 p-3 text-sm">{error}</p>}<form onSubmit={(e) => { e.preventDefault(); load() }} className="mt-7 grid gap-4 border border-ink/15 bg-panel p-4 sm:grid-cols-4"><label className="text-sm font-semibold">Doctor<select value={filters.doctor} onChange={(e) => setFilters({ ...filters, doctor: e.target.value })} className="mt-2 w-full border border-ink/25 p-2 font-normal"><option value="">All doctors</option>{doctors.map((doctor) => <option value={doctor.id} key={doctor.id}>{doctor.name}</option>)}</select></label><label className="text-sm font-semibold">Date<input type="date" value={filters.date} onChange={(e) => setFilters({ ...filters, date: e.target.value })} className="mt-2 w-full border border-ink/25 p-2 font-normal" /></label><label className="text-sm font-semibold">Status<select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })} className="mt-2 w-full border border-ink/25 p-2 font-normal"><option value="">All statuses</option>{statuses.map((s) => <option key={s} value={s}>{s[0].toUpperCase() + s.slice(1)}</option>)}</select></label><button className="self-end bg-ink px-4 py-2.5 text-sm font-bold text-panel">Apply filters</button></form>{loading ? <p className="mt-8 text-sm text-ink/60">Loading appointments...</p> : items.length ? <div className="mt-6 overflow-x-auto border border-ink/15 bg-panel"><table className="w-full min-w-225 text-sm"><thead className="bg-ink text-left text-panel/75"><tr>{['Patient', 'Doctor', 'Date', 'Time', 'Status', 'Clinical notes', 'Update'].map((x) => <th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t border-ink/10 align-top"><td className="p-4 font-semibold">{item.patient_username}</td><td className="p-4">{item.doctor_name}</td><td className="p-4">{item.date}</td><td className="p-4">{item.scheduled_time?.slice(0, 5)}</td><td className="p-4"><AppointmentStatus status={item.status}/></td><td className="max-w-80 whitespace-pre-wrap p-4 text-xs"><b>Diagnosis:</b> {item.diagnosis || '—'}<br/><b>Treatment:</b> {item.treatment || '—'}</td><td className="p-4"><select disabled={saving === item.id} value={item.status} onChange={(e) => changeStatus(item.id, e.target.value)} className="border border-ink/25 p-2 text-xs disabled:opacity-50">{statuses.map((s) => <option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div> : <p className="mt-6 border border-ink/15 bg-panel p-5 text-sm text-ink/65">No appointments match these filters.</p>}</div> }
